packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@google/genai': false
  cpu-features: false
  electron-winstaller: true
  esbuild: true
  protobufjs: false
  ssh2: false
minimumReleaseAgeExclude:
  - electron@42.4.0
  - prettier@3.8.4
  - '@earendil-works/pi-agent-core@0.79.1'
  - '@earendil-works/pi-ai@0.79.1'
